// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yatzoo.Data;

namespace yatzoo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190125225347_DbSetup")]
    partial class DbSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("yatzoo.Models.Game", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("yatzoo.Models.Lobby", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("lobbies");
                });

            modelBuilder.Entity("yatzoo.Models.Message", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("contents")
                        .IsRequired();

                    b.Property<Guid>("lobbyId");

                    b.Property<DateTimeOffset>("postedAt");

                    b.Property<string>("username")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("yatzoo.Models.Player", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("Lobbyid");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("Lobbyid");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("yatzoo.Models.Player", b =>
                {
                    b.HasOne("yatzoo.Models.Lobby")
                        .WithMany("players")
                        .HasForeignKey("Lobbyid");
                });
#pragma warning restore 612, 618
        }
    }
}
